# -*- coding: utf-8 -*-
"""%%writefile student_utils.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jrI3S_8Rao38OmgIImfAnTKYtie-FEHR
"""

PASS_MARK = 40

def calculate_average(marks):
    total = 0

    for m in marks:
        total = total + m

    return total / (len(marks)-1)


def is_passing(mark):
    if mark > PASS_MARK:
        return True

    return False


def get_grade(average):
    if average >= 60:
        return "First"

    elif average >= 45:
        return "Second"

    elif average >= 90:
        return "Distinction"

    return "Fail"

calculate_average([80,90,100])